#!/usr/bin/env python3
"""Build the Java source bundle represented by the public KLite API website.

The website API reference is generated from the direct Java source files in the
KLite client API, automation runtime, and web-walker packages. This script
packages that exact documented surface and rejects any drift between the source
tree and the generated website reference.
"""

from __future__ import annotations

import hashlib
import json
import os
import re
import sys
import zipfile
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
JAVA_ROOT = ROOT / "runelite-client" / "src" / "main" / "java"
KLITE_ROOT = JAVA_ROOT / "net" / "runelite" / "client" / "plugins" / "klite"
REFERENCE_FILE = ROOT / "marketplace-site" / "worker" / "api-reference.generated.js"
OUTPUT_ROOT = ROOT / "dist" / "plugin-sdk"
BUNDLE_NAME = "KLite-Public-API-Sources.zip"
BUNDLE_ROOT = "KLite-Public-API-Sources"

AREAS = (
    ("Client API", "api"),
    ("Automation runtime", "automation"),
    ("Web walker", "walker"),
)

TYPE_PATTERN = re.compile(
    r"public\s+(?:(?:final|abstract|sealed)\s+)?"
    r"(class|interface|enum|record)\s+(\w+)"
)
PACKAGE_PATTERN = re.compile(r"package\s+([\w.]+);")


@dataclass(frozen=True)
class PublicType:
    area: str
    name: str
    kind: str
    package_name: str
    source_path: Path

    @property
    def relative_java_path(self) -> Path:
        return self.source_path.relative_to(JAVA_ROOT)


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def add_bytes(archive: zipfile.ZipFile, name: str, data: bytes) -> None:
    info = zipfile.ZipInfo(name)
    info.date_time = (2026, 1, 1, 0, 0, 0)
    info.compress_type = zipfile.ZIP_DEFLATED
    info.external_attr = 0o644 << 16
    archive.writestr(info, data)


def documented_reference() -> dict:
    source = REFERENCE_FILE.read_text("utf-8")
    prefix = "export const API_REFERENCE = "
    if not source.startswith("// Generated by") or prefix not in source:
        raise RuntimeError(f"Unsupported API reference format: {REFERENCE_FILE}")
    payload = source.split(prefix, 1)[1].strip()
    if not payload.endswith(";"):
        raise RuntimeError(f"Generated API reference is missing its terminator: {REFERENCE_FILE}")
    return json.loads(payload[:-1])


def discover_public_types() -> list[PublicType]:
    public_types: list[PublicType] = []
    for area, directory_name in AREAS:
        directory = KLITE_ROOT / directory_name
        if not directory.is_dir():
            raise FileNotFoundError(f"Public API source directory does not exist: {directory}")
        for source_path in sorted(directory.glob("*.java")):
            source = source_path.read_text("utf-8")
            package_match = PACKAGE_PATTERN.search(source)
            type_match = TYPE_PATTERN.search(source)
            if not package_match or not type_match:
                continue
            public_types.append(
                PublicType(
                    area=area,
                    name=type_match.group(2),
                    kind=type_match.group(1),
                    package_name=package_match.group(1),
                    source_path=source_path,
                )
            )
    return public_types


def verify_reference_parity(public_types: list[PublicType], reference: dict) -> None:
    documented = {
        (section["name"], item["packageName"], item["name"], item["kind"])
        for section in reference.get("sections", [])
        for item in section.get("types", [])
    }
    discovered = {
        (item.area, item.package_name, item.name, item.kind)
        for item in public_types
    }
    missing_from_bundle = sorted(documented - discovered)
    undocumented_sources = sorted(discovered - documented)
    if missing_from_bundle or undocumented_sources:
        details = []
        if missing_from_bundle:
            details.append(f"missing documented types: {missing_from_bundle}")
        if undocumented_sources:
            details.append(f"undocumented source types: {undocumented_sources}")
        raise RuntimeError(
            "Public API sources do not match api-reference.generated.js; "
            + "; ".join(details)
            + ". Run `npm run api:generate` in marketplace-site when the API changes."
        )
    expected_count = int(reference.get("typeCount", -1))
    if expected_count != len(public_types):
        raise RuntimeError(
            f"API reference declares {expected_count} types but {len(public_types)} source files were found"
        )


def bundle_readme(version: str, commit: str, count: int) -> bytes:
    return (
        "# KLite Public API Sources\n\n"
        "This archive contains the exact Java source types displayed by the KLite "
        "API reference and used by the plugin-development documentation.\n\n"
        f"- API bundle version: `{version}`\n"
        f"- Source commit: `{commit}`\n"
        f"- Public Java types: `{count}`\n"
        "- Areas: Client API, Automation runtime, Web walker\n\n"
        "Marketplace, account, updater, launcher, and other private implementation "
        "packages are intentionally excluded. The source bundle is a reference "
        "companion to `KLite-Plugin-SDK.jar`; use the SDK JAR as the compile-only "
        "dependency in plugin projects.\n"
    ).encode("utf-8")


def build_source_bundle(version: str) -> Path:
    reference = documented_reference()
    public_types = discover_public_types()
    verify_reference_parity(public_types, reference)

    commit = os.environ.get("GITHUB_SHA", "local")
    manifest = {
        "schemaVersion": 1,
        "bundleVersion": version,
        "sourceCommit": commit,
        "scope": reference.get("scope", ""),
        "typeCount": len(public_types),
        "methodCount": reference.get("methodCount"),
        "areas": [
            {
                "name": area,
                "types": [
                    {
                        "name": item.name,
                        "kind": item.kind,
                        "packageName": item.package_name,
                        "sourcePath": (
                            Path("src") / "main" / "java" / item.relative_java_path
                        ).as_posix(),
                    }
                    for item in public_types
                    if item.area == area
                ],
            }
            for area, _ in AREAS
        ],
    }

    OUTPUT_ROOT.mkdir(parents=True, exist_ok=True)
    output = OUTPUT_ROOT / BUNDLE_NAME
    with zipfile.ZipFile(output, "w") as archive:
        add_bytes(
            archive,
            f"{BUNDLE_ROOT}/README.md",
            bundle_readme(version, commit, len(public_types)),
        )
        add_bytes(
            archive,
            f"{BUNDLE_ROOT}/api-sources-manifest.json",
            (json.dumps(manifest, indent=2) + "\n").encode("utf-8"),
        )
        for item in public_types:
            destination = (
                Path(BUNDLE_ROOT) / "src" / "main" / "java" / item.relative_java_path
            ).as_posix()
            add_bytes(archive, destination, item.source_path.read_bytes())

    with zipfile.ZipFile(output) as archive:
        corrupt_entry = archive.testzip()
        if corrupt_entry:
            raise RuntimeError(f"Generated API source ZIP contains a corrupt entry: {corrupt_entry}")

    print(
        f"Built {output} with {len(public_types)} documented Java types; "
        f"SHA-256 {sha256(output)}"
    )
    return output


def main() -> int:
    version = os.environ.get("KLITE_SDK_VERSION", "0.0.0-local").strip()
    try:
        build_source_bundle(version)
    except Exception as exception:  # noqa: BLE001 - command-line build reports complete failures
        print(f"API source bundle build failed: {exception}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
