import assert from "node:assert/strict";
import { execFile } from "node:child_process";
import { readFile } from "node:fs/promises";
import path from "node:path";
import test from "node:test";
import { promisify } from "node:util";
import { fileURLToPath } from "node:url";

const execFileAsync = promisify(execFile);
const testDirectory = path.dirname(fileURLToPath(import.meta.url));
const siteDirectory = path.resolve(testDirectory, "..");

test("homepage serves one deterministic generated stylesheet", async () => {
  await execFileAsync(process.execPath, ["scripts/build-home-styles.mjs", "--check"], { cwd: siteDirectory });

  const [html, stylesheet] = await Promise.all([
    readFile(path.join(siteDirectory, "public/index.html"), "utf8"),
    readFile(path.join(siteDirectory, "public/home.css"), "utf8"),
  ]);

  const stylesheetLinks = html.match(/<link\s+rel="stylesheet"/g) ?? [];
  assert.equal(stylesheetLinks.length, 1);
  assert.match(html, /href="\/home\.css\?v=20260718-1" data-klite-resources-menu/);
  assert.match(stylesheet, /^\/\* Generated by scripts\/build-home-styles\.mjs\./);
  assert.match(stylesheet, /\/\* Source: preview-match\.css \*\//);
  assert.match(stylesheet, /\/\* Source: resources-menu\.css \*\//);
});

test("homepage primary navigation contains one marketplace destination", async () => {
  const html = await readFile(path.join(siteDirectory, "public/index.html"), "utf8");
  const navigation = html.match(/<nav class="primary-site-nav"[\s\S]*?<\/nav>/)?.[0];

  assert.ok(navigation, "primary navigation is missing");
  assert.equal((navigation.match(/data-site-route="marketplace"/g) ?? []).length, 1);
  assert.doesNotMatch(navigation, /href="#marketplace"[^>]*>[\s\S]*?Plugins<\/a>/);
});
